### ISSUE TITLE
Goals to http & tools topics

### ISSUE THREAD

**Issue by bee0060** [JSA-AAA/study#50]
http (add to goal, need answer questions)

    - 发送请求的用户通过了身份验证，但是没有当前操作的权限时，应该返回什么状态码？
    - 更新应该用什么method
    - 以下API符合restful吗？为什么? 怎么改成符合restful
        - （更新用户信息） POST /users/1/updateUserDetail 
        - （获取用户详情） POST /users/1/getUserDetail

tools ( add to goal)

    - 实现的功能可以很简单，只要有基本的增删查改（CRUD)即可。
    - generate coverage report
    - 用express实现4个API， method分别是GET\POST\PUT\DELETE。并且在前端成功调用。
    - eslint如何配置自己的规则？
    - babel配置中的preset用于设置什么？
    - webpack中的output用于配置什么？
    - webpack的loader和plugin分别是什么，有什么区别？
    - webpack中如何开启热更新（hot-reload)?
    - webpack中的sourcemap有什么用？

**Comment by yuhao3570** [comment]
thanks, Steven!
